version: "3"

services:
  noobeecamp-db-service:
    build:
      context: .
      dockerfile: dockerfile
    image: noobeecamp-db-service
    container_name: noobeecamp-db-services
    restart: always
    networks:
      - app-network
  
  webserver:
    image: nginx
    container_name: websrever
    restart: always
    ports:
      - "9999:80"
    volumes:
      - web-root:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - noobeecamp-db-service
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email reyhanjovie01@gmail.com --agree-tos --no-eff-email --staging -d 103.214.113.109  -d www.103.214.113.109.com

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/sammy/node_project/views/
      o: bind

networks:
  app-network:
    driver: bridge